### ISSUE TITLE
Using this plugin in browser?

### ISSUE THREAD

**Issue by canebat** [tatsy/markdown-it-imsize#5]
Hello, thanks for this plugin. Can you provide example how to load it in browser?

ie,

```
<script>
    var md = window.markdownit();
    var result = md.render('![image](https://octodex.github.com/images/minion.png =50x)');
</script>
```

**Comment by tatsy** [comment]
Hello, @canebat. Thank you for your interest for this plugin.

In order to use this plugin (and also original markdown-it) in browser, you have to use [RequireJS](http://requirejs.org/) or other similar packages to enable us to use node.js "require" in non-node.js environment.

If you provide me the detail of your environment, maybe I can show you a clearer way to use this plugin.

Thanks.

**Comment by canebat** [comment]
@tatsy Oh okay, I will take a look at RequireJS. 

Would it be possible to support loading it directly into the page?  The [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) plugin has that ability:

```
var md = window.markdownit().use(window.markdownitEmoji);
```

**Comment by tatsy** [comment]
@canebat I'm sorry but you need to use require.js for this plugin. So you cannot load directly into the page. Following is the whole codes to call this plugin with require.js. 

If you have any other questions, please do not hesitate to ask me. Thanks.

#### index.html

``` html
<html>
<head>
  <script src="/path/to/markdown-it.min.js"></script>
  <script src="/path/to/markdown-it-imsize.min.js"></script>
  <script src="/path/to/require_config.js"></script>
  <script src="/path/to/require.js"></script>
</head>

<body>
  <div id="image-box"></div>
  <script>
    require(['require', 'MarkdownItImsize'], function(require) {
      var md = window.markdownit({
        html: true,
        linkify: true,
        typography: true
      }).use(require('MarkdownItImsize'));

      // Your code using markdwon-it-imsize below
      document.getElementById('image-box').innerHTML = md.render('![test](test.jpg =100x200)');
    });
  </script>
</body>
</html>
```

#### require_config.js

``` js
var require = {
  paths: {
    // Be careful, you don't have to add '.js' after the file name
    'MarkdownItImsize': '/path/to/markdown-it-imsize.min'
  }
};

```

**Comment by canebat** [comment]
Ok, thanks. This is a bit off topic, but I am also using nodejs and I was wondering what a good way to do error handling for this would be?

```
// node.js version
var md = require('markdown-it')({
  html: true,
  linkify: true,
  typography: true
}).use(require('markdown-it-imsize')); 

md.render(...);      // some kind of error handling here?
```
