### ISSUE TITLE
Multiple image resolutions

### ISSUE THREAD

**Issue by unindented** [tatsy/markdown-it-imsize#7]
How hard would it be to implement `srcset` generation? So if I have `foo.png` and `foo@2x.png`, then this:

``` markdown
![](foo.png)
```

Would generate this:

```
<img src="foo.png" srcset="foo.png 1x, foo@2x.png 2x" alt="" width="256" height="256" />
```

**Comment by tatsy** [comment]
Hello, @unindented.

Actually, I got a similar question before and I made a different package `markdown-it-responsive` to support responsive images.

[markdown-it-responsive](https://github.com/tatsy/markdown-it-responsive)

I think the functional you mentioned is close to this. First, please take a look at this repository. To be honest, I don't update `markdown-it-reponsive`, so you may have a problem. If so, could you open a new issue?

Thank you.

**Comment by unindented** [comment]
@tatsy will do, thank you very much.
